# Site settings
title:          Abdullah Al Imran
description:    "{Data Science & ML Aficionado, Wisdom Seeker}"
baseurl:        ""
url:            ""

# Avatar
avatar: /images/abdalimran-logo.png

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: abdullah-al-imran

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-87754832-1

# Author
author:
  name:             Imran
  url:              https://abdalimran.github.io
  email:            abdalimran@gmail.com
  facebook:         abdalimran
  twitter:          AbdullahAlImran
  github:           abdalimran
  stackoverflow:    abdalimran
  quora:            Abdullah-Al-Imran-1
  linkedin:         abdalimran
  googlePlus:       abdalimran
  reddit:           abdalimran
  medium:           abdalimran
  rss:              feed.xml

# Copyright Info
copyright:
  year:             2020
  name:             Abdullah Al Imran


# Build settings
markdown:       kramdown


# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
